spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: jdbc:postgresql://${LOCAL_DB_URL}/${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:myDefaultSecretKeyForJWT123456789012345678901234567890}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}  # 24 hours in milliseconds

google:
  gemini:
    api-key: ${GEMINI_API_KEY}

openai:
    api-key: ${OPENAI_API_KEY}
    model: ${OPENAI_MODEL}
server:
  port: 8080


vnpay:
  tmn:
    code: ${VNPAY_TMN_CODE}
  hash:
    secret: ${VNPAY_HASH_SECRET}
  pay:
    url: ${VNPAY_PAY_URL}
  return:
    url: ${VNPAY_RETURN_URL}


