spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: jdbc:postgresql://${LOCAL_DB_URL}/${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

google:
  gemini:
    api-key: ${GEMINI_API_KEY}


vnpay:
  tmn:
    code: ${VNPAY_TMN_CODE}
  hash:
    secret: ${VNPAY_HASH_SECRET}
  pay:
    url: ${VNPAY_PAY_URL}
  return:
    url: ${VNPAY_RETURN_URL}


